fi_gains_toolControl:
  topic: '/mixed_platform/platform_state'
  toolPos: 
    p_a: [0.0,0.0,0.0,2000.0,800.0] # assymetric p gains, to make it easier to move e.g. in abduction w.r.t adduction
    p_b: [0.0,0.0,0.0,10000.0,1000.0]
    #p_a: [0.0,0.0,0.0,2000.0,1000.0] # symetric p gains, to make it easier to move e.g. in abduction w.r.t adduction
    #p_b: [0.0,0.0,0.0,2000.0,1000.0]
    d: [20.0,20.0,200.0,200.0,200.0]
  toolSpeed:
    p_a: [100.0,100.0,3000.0,5000.0,800.0] # original
    p_b: [250.0,250.0,10000.0,5000.0,1000.0]
    
    # p_a: [50.0,50.0,200.0,20000.0,500.0] #bernardo asymmetric
    # p_b: [100.0,100.0,10000.0,20000.0,1000.0]
    
    # p_a: [100.0,100.0,3000.0,5000.0,800.0] # farshad
    # p_b: [250.0,250.0,10000.0,5000.0,1000.0]

    # p_a: [50.0,50.0,2000.0,3000.0,300.0] # carolina
    # p_b: [50.0,50.0,2000.0,3000.0,300.0]

    d: [20.0,20.0,200.0,200.0,200.0]
  toolMixed:  # the auxiliary platform
    p_a: [100.0,100.0,0.0,10000.0,800.0]
    p_b: [250.0,250.0,0.0,10000.0,1000.0]
    d: [30.0,30.0,60.0,60.0,60.0]