toolControl:
  topic: '/mixed_platform/platform_state'
  toolPos: 
    p: [0.0,0.0,0.0,10000.0,1000.0]
    d: [10.0,10.0,100.0,100.0,100.0]
  toolSpeed:
    p: [1000.0,1000.0,2500.0,10000.0,1000.0]
    d: [10.0,10.0,100.0,100.0,100.0]
  toolMixed:  
    p: [1000.0,1000.0,0.0,10000.0,1000.0]
    d: [10.0,10.0,100.0,100.0,100.0]