toolControl_gains:
  topic: 
    - 'mixedPlatform/platformState'
  position_control_tool:
    kp: [0.0 , 0.0, 0.0, 5000.0, 0.0]]
    ki: [0.0, 0.0, 0.0, 0.0, 0.0]
    kd: [10.0, 10.0, 100.0, 100.0, 100.0]
  speed_control_tool:
    kp: [0.0, 0.0, 0.0, 5000.0, 0.0] 
    ki: [0.0, 0.0, 0.0, 0.0, 0.0]
    kd: [10.0, 10.0, 100.0, 100.0, 100.0]
