#These you can measure in the subject and update
thigh_width: 0.290 # not from the model, but measured
thigh_depth: 0.200 # not from the model, but measured
shin_width: 0.135 # not from the model, but measured
shin_depth: 0.135 # not from the model, but measured
foot_length: 0.270 # not from the model, but measured
thigh_length: 0.43
shin_length:  0.38
ankle_to_foot_base_z: 0.080
ankle_to_foot_base_x: 0.046
foot_base_to_foot_tip: 0.17667
body_weight: 90
hip_width: 0.24
hip_height: 0.9246
