/right_tool:
  toolType: 'forceps'
  toolSelfRotationControl: 'position'
  #speedControlGainCamera: 0.5
  speedControlGainSelfRotation: 50.0
  desiredPlatformWorkspaceLimsMin: [-0.090, -0.0975, -0.200, 0.00000, -0.349066] # Y,X,PITCH,ROLL,YAW
  desiredPlatformWorkspaceLimsMax: [0.090, 0.0975, 0.0872665, 0.261799, 0.349066]
  deadZoneValuesPlatformMin: [-0.05, -0.05, -0.18, -0.15, -0.08]
  deadZoneValuesPlatformMax: [0.05, 0.05, 0.00, 0.15, 0.08]
  platformJointOffsets: [0.0, 0.0, 0.0, 0.0, 0.0]
  cartLimsX: [-0.15,0.15] # [m]
  cartLimsY: [-0.10,0.10]  # [m]
  cartLimsZ: [-0.26,-0.03] # [m]