/right_tool:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
    joints_names:
      - right_tool_joint1_pitch
      - right_tool_joint2_roll
      - right_tool_joint3_yaw
      - right_tool_joint4_insertion

  joint_position_controller:
    type: position_controllers/JointGroupPositionController
    robot_description: /right_tool/robot_description
    joints:
      - right_tool_joint1_pitch
      - right_tool_joint2_roll
      - right_tool_joint3_yaw
      - right_tool_joint4_insertion
    right_tool_joint1_pitch: 
      pid: {p: 10000, i: 0 , d: 50, i_clamp_min: -1000.0, i_clamp_max: 1000.0, antiwindup: true }
    right_tool_joint2_roll: 
      pid: {p: 10000, i: 0 , d: 50, i_clamp_min: -1000.0, i_clamp_max: 1000.0, antiwindup: true }
    right_tool_joint3_yaw:
      pid: {p: 500, i: 0, d: 5, i_clamp_min: -1000.0, i_clamp_max: 1000.0, antiwindup: true }
    right_tool_joint4_insertion: 
      pid: {p: 10000, i: 0 , d: 50, i_clamp_min: -1000.0, i_clamp_max: 1000.0, antiwindup: true }
  # gazebo_ros_control:
  #   pid_gains:
  #     right_tool_joint4_insertion: {p: 10000, i: 0, d: 1000}
  #     right_tool_joint1_pitch: {p: 10000, i: 0, d: 1000}
  #     right_tool_joint2_roll: {p: 10000, i: 0, d: 1000}
  #     right_tool_joint3_yaw: {p: 1000, i: 0, d: 500}
  # Position Controllers ---------------------------------------