/right_tool:
  toolType: 'forceps'
  toolSelfRotationControl: 'position'
  #speedControlGainCamera: 0.5
  #speedControlGainSelfRotation: 50.0
  deadZoneValuesPlatform: [0.0180, 0.0195, 0.0959931, 0.0715585, 0.0436332]