/right_tool:
  toolType: 'forceps'
  toolSelfRotationControl: 'speed'
  speedControlGainCamera: 0.5
  speedControlGainSelfRotation: 10.0
  desiredPlatformWorkspaceLimsMin: [-0.090, -0.0975, -0.200, 0.000, -0.349066] # Y,X,PITCH,ROLL,YAW
  desiredPlatformWorkspaceLimsMax: [0.090, 0.0975, 0.0872665, 0.126892, 0.349066] #[0.090, 0.0975, 0.0872665, 0.226892, 0.349066]
  deadZoneValuesPlatformMin: [-0.05, -0.05, -0.18, -0.15, -0.26]
  deadZoneValuesPlatformMax: [0.05, 0.05, 0.00, 0.15, 0.03]
  platformJointOffsets: [0.0, 0.0, 0.0, -0.15, 0.0]
  cartLimsX: [-0.15,0.10] # [m]
  cartLimsY: [-0.10,0.10]  # [m]
  cartLimsZ: [-0.26,-0.03] # [m]