surgical_tool:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  tool_yaw_position_ctrl:
    type: effort_controllers/JointPositionController
    joint: tool_yaw
    pid: {p: 300.0, i: 0.0, d: 60.0}
  tool_pitch_position_ctrl:
    type: effort_controllers/JointPositionController
    joint: tool_pitch
    pid: {p: 300.0, i: 0.0, d: 60.0}
  tool_insertion_position_ctrl:
    type: effort_controllers/JointPositionController
    joint: tool_insertion
    pid: {p: 300.0, i: 0.0, d: 60.0}
  tool_roll_position_ctrl:
    type: effort_controllers/JointPositionController
    joint: tool_roll
    pid: {p: 300.0, i: 0.0, d: 60.0}  
  tool_wrist_pitch_joint_position_ctrl:
    type: effort_controllers/JointPositionController
    joint: tool_wrist_pitch
    pid: {p: 300.0, i: 0.0, d: 60.0}   
  tool_wrist_yaw_joint_position_ctrl:
    type: effort_controllers/JointPositionController
    joint: tool_wrist_yaw
    pid: {p: 300.0, i: 0.0, d: 60.0}    
  tool_wrist_open_angle_joint_position_ctrl:
    type: effort_controllers/JointPositionController
    joint: tool_wrist_open_angle
    pid: {p: 300.0, i: 0.1, d: 60.0}    