#These you can measure in the subject and update
thigh_width: 0.170		
thigh_depth: 0.175 
shin_width: 0.115 
shin_depth: 0.115
foot_length: 0.250 
thigh_length: 0.410
shin_length:  0.375
ankle_to_foot_base_z: 0.125
ankle_to_foot_base_x: 0.040
foot_base_to_foot_tip: 0.145
body_weight: 53
hip_width: 0.200
hip_height: 0.98
