#These you can measure in the subject and update
thigh_width: 0.16 
thigh_depth: 0.21 
shin_width: 0.105 
shin_depth: 0.105
foot_length: 0.260 
thigh_length: 0.400
shin_length:  0.420
ankle_to_foot_base_z: 0.100
ankle_to_foot_base_x: 0.065
foot_base_to_foot_tip: 0.155
body_weight: 80
hip_width: 0.240
hip_height: 0.935
