#These you can measure in the subject and update
#Farshad Kadhivar
thigh_width: 0.170 
thigh_depth: 0.170 
shin_width: 0.115 
shin_depth: 0.115 
foot_length: 0.260 
thigh_length: 0.395
shin_length:  0.390
ankle_to_foot_base_z: 0.105
ankle_to_foot_base_x: 0.0505
foot_base_to_foot_tip: 0.155
body_weight: 68
hip_width: 0.260
hip_height: 0.900 
