#These you can measure in the subject and update
#Jacob 0.790+ 0.165+0.080
thigh_width: 0.290 
thigh_depth: 0.200 
shin_width: 0.135 
shin_depth: 0.135 
foot_length: 0.270 
thigh_length: 0.420
shin_length:  0.380
ankle_to_foot_base_z: 0.100
ankle_to_foot_base_x: 0.020
foot_base_to_foot_tip: 0.15621
body_weight: 84
hip_width: 0.24
hip_height: 1.035 
