rokubiminis:
  - name:                     ROKUBIMINI_LF_A
    configuration_file:       rokubimini_a.yaml
    product_code:             1
    port:                     /dev/ttyUSB0
    baud_rate:                500000
  # - name:                     ROKUBIMINI_LF_B
  #   configuration_file:       rokubimini_a.yaml
  #   product_code:             2
  #   ethercat_bus:             enxd8eb97bf8390
  #   ethercat_address:         1
  #   ethercat_pdo_type:        Z