rokubiminis:
  - name: ft_sensor_right
    configuration_file: rokubimini_sensor.yaml
    product_code: 1
    port: /dev/right_force_sensor
    baud_rate: 460800
#  - name:                     ft_sensor1
#    configuration_file:       rokubimini_sensor.yaml
#    product_code:             2
#    ethercat_bus:             enx3c8cf8ea282c
#    ethercat_address:         1
#    ethercat_pdo_type:        A #EXTIMU


