#These you can measure in the subject and update
#walid amanhoud #s5 
#0.790+ 0.165+0.070
thigh_width: 0.150
thigh_depth: 0.190
shin_width: 0.130
shin_depth: 0.135
foot_length: 0.265
thigh_length: 0.470
shin_length:  0.435
ankle_to_foot_base_z: 0.105
ankle_to_foot_base_x: 0.040
foot_base_to_foot_tip: 0.170
body_weight: 69.5
hip_width: 0.260
hip_height: 1.025
