#These you can measure in the subject and update
thigh_width: 0.190 
thigh_depth: 0.200 
shin_width: 0.140 
shin_depth: 0.140
foot_length: 0.290 
thigh_length: 0.440
shin_length:  0.450
ankle_to_foot_base_z: 0.105
ankle_to_foot_base_x: 0.050
foot_base_to_foot_tip: 0.200
body_weight: 80
hip_width: 0.260
hip_height: 0.945
