#These you can measure in the subject and update
thigh_width: 0.160 
thigh_depth: 0.210 
shin_width: 0.135 
shin_depth: 0.135 
foot_length: 0.290 
thigh_length: 0.440
shin_length:  0.425
ankle_to_foot_base_z: 0.115
ankle_to_foot_base_x: 0.060
foot_base_to_foot_tip: 0.195
body_weight: 58
hip_width: 0.24
hip_height: 0.83 
