# /left_tool:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
    joints_names:
      - left_tool_insertion
      - left_tool_pitch
      - left_tool_roll
      - left_tool_wrist_open_angle
      - left_tool_wrist_open_angle_mimic
      - left_tool_yaw

  joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - left_tool_insertion
      - left_tool_pitch
      - left_tool_roll
      - left_tool_wrist_open_angle
      - left_tool_wrist_open_angle_mimic
      - left_tool_yaw
  gazebo_ros_control:
    pid_gains:
      left_tool_insertion: {p: 10000, i: 0, d: 1000}
      left_tool_pitch: {p: 10000, i: 0, d: 1000}
      left_tool_roll: {p: 10000, i: 0, d: 1000}
      left_tool_wrist_open_angle: {p: 1000, i: 0, d: 30}
      left_tool_wrist_open_angle_mimic: {p: 1000, i: 0, d: 30}
      left_tool_yaw: {p: 1000, i: 0, d: 500}
      #left_tool_wrist_pitch: {p: 0, i: 0, d: 60}
      #left_tool_wrist_yaw: {p: 0, i: 0, d: 60}
  # Position Controllers ---------------------------------------