left_panda:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  # in Hz

  joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
      - left_panda_tool_wrist_open_angle
      - left_panda_tool_wrist_open_angle_mimic
  # /gazebo_ros_control:
  #   pid_gains:
  #     left_panda_joint1: {p: 10000, i: 0, d: 50}
  #     left_panda_joint2: {p: 10000, i: 0, d: 500}
  #     left_panda_joint3: {p: 1000, i: 0, d: 50}
  #     left_panda_joint4: {p: 1000, i: 0, d: 50}
  #     left_panda_joint5: {p: 100, i: 0, d: 50}
  #     left_panda_joint6: {p: 100, i: 0, d: 50}
  #     left_panda_joint7: {p: 100, i: 0, d: 50}
  #     left_panda_tool_wrist_open_angle: {p: 100, i: 0, d: 50}
  #     left_panda_tool_wrist_open_angle_mimic: {p: 100, i: 0, d: 50}