#These you can measure in the subject and update
#Seif
#constant: 1 - 26/59
thigh_width: 0.170
thigh_depth: 0.170 
shin_width: 0.120
shin_depth: 0.130
foot_length: 0.260
thigh_length: 0.395
shin_length:  0.420
ankle_to_foot_base_z: 0.105
ankle_to_foot_base_x: 0.055
foot_base_to_foot_tip: 0.160
body_weight: 81
hip_width: 0.300
hip_height: 0.910
